/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagementRole;

import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.LegalDepartmentOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class FosterParentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FosterParentJPanel
     */
    JPanel userProcessContainer;
    LabTestWorkRequest request;
    Enterprise enterprise;

    FosterParentJPanel(JPanel userProcessContainer, LabTestWorkRequest request, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.enterprise = enterprise;
        populateFields();
    }
    
    public void populateFields(){
        txtChildName.setText(request.getChildName());
        txtSex.setText(request.getSex());
        txtEthnicity.setText(request.getEthnicity());
        ImageIcon imageIcon = new ImageIcon(request.getImagePath());
        lblImage.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAnnualIncome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtLiabilities = new javax.swing.JTextField();
        txtPartner = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSavings = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtChildName = new javax.swing.JTextField();
        txtSex = new javax.swing.JTextField();
        txtEthnicity = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtsex = new javax.swing.JTextField();

        jLabel4.setText("Age");

        jLabel6.setText("Occupation");

        jLabel15.setText("Sex");

        setBackground(new java.awt.Color(177, 201, 226));
        setLayout(null);

        txtFirstName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtFirstName);
        txtFirstName.setBounds(699, 205, 250, 23);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("First Name:");
        add(jLabel1);
        jLabel1.setBounds(581, 210, 73, 17);

        txtLastName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtLastName);
        txtLastName.setBounds(700, 250, 250, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Last Name:");
        add(jLabel2);
        jLabel2.setBounds(584, 255, 71, 17);

        txtAge.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtAge);
        txtAge.setBounds(700, 290, 60, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Age:");
        add(jLabel3);
        jLabel3.setBounds(620, 290, 190, 30);

        txtOccupation.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtOccupation);
        txtOccupation.setBounds(700, 370, 250, 23);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Occupation:");
        add(jLabel5);
        jLabel5.setBounds(580, 370, 74, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Sex:");
        add(jLabel7);
        jLabel7.setBounds(626, 330, 30, 20);

        txtSSN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });
        add(txtSSN);
        txtSSN.setBounds(700, 410, 250, 23);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Social Security Number:");
        add(jLabel8);
        jLabel8.setBounds(510, 407, 149, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Annual Income ($):");
        add(jLabel9);
        jLabel9.setBounds(540, 450, 121, 30);

        txtAnnualIncome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtAnnualIncome);
        txtAnnualIncome.setBounds(700, 450, 250, 23);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Liabilities if Any ($):");
        add(jLabel10);
        jLabel10.setBounds(530, 490, 130, 30);

        txtLiabilities.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtLiabilities);
        txtLiabilities.setBounds(700, 490, 250, 23);

        txtPartner.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartnerActionPerformed(evt);
            }
        });
        add(txtPartner);
        txtPartner.setBounds(700, 530, 250, 23);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Spouse / Partner's full Name:");
        add(jLabel11);
        jLabel11.setBounds(480, 530, 181, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Savings / FD's /Shares if Any ($):");
        add(jLabel12);
        jLabel12.setBounds(460, 580, 205, 30);

        txtSavings.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtSavings);
        txtSavings.setBounds(700, 580, 250, 23);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(590, 640, 176, 40);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Child Name:");
        add(jLabel13);
        jLabel13.setBounds(79, 225, 77, 17);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Sex:");
        add(jLabel14);
        jLabel14.setBounds(131, 270, 27, 17);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Ethnicity:");
        add(jLabel16);
        jLabel16.setBounds(96, 315, 60, 17);

        txtChildName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtChildName);
        txtChildName.setBounds(193, 220, 200, 23);

        txtSex.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtSex);
        txtSex.setBounds(193, 265, 98, 23);

        txtEthnicity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtEthnicity);
        txtEthnicity.setBounds(193, 310, 200, 23);

        lblImage.setText(".");
        add(lblImage);
        lblImage.setBounds(40, 380, 380, 330);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setText("Enter Foster Parent details");
        add(jLabel17);
        jLabel17.setBounds(420, 90, 280, 29);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(28, 27, 77, 37);
        add(txtsex);
        txtsex.setBounds(700, 330, 64, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartnerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ssnval = "^\\d{10}";
        Pattern pat3 = Pattern.compile(ssnval);
        Matcher mat3 = pat3.matcher(txtSSN.getText());
        if(!mat3.matches()){
        JOptionPane.showMessageDialog(null, "Invalid SSN");
        }
        else if(txtFirstName.getText()==null||txtFirstName.getText().isEmpty()||txtLastName.getText()==null||txtLastName.getText().isEmpty()||txtAge.getText()==null||txtAge.getText().isEmpty()||txtSex.getText()==null||txtSex.getText().isEmpty()||txtOccupation.getText()==null||txtOccupation.getText().isEmpty()||txtSSN.getText()==null||txtSSN.getText().isEmpty()||txtAnnualIncome.getText()==null||txtAnnualIncome.getText().isEmpty())
        {
                        JOptionPane.showMessageDialog(null, "One or more mandatory text fields might be empty");

        }
        else{
            try{
        request.setParent(txtFirstName.getText()+" "+txtLastName.getText());
        request.setAge(Integer.parseInt(txtAge.getText()));
        request.setParentsex((String)(txtsex.getText()));
        request.setOccupation(txtOccupation.getText());
        request.setSSN(Double.parseDouble(txtSSN.getText()));
        request.setAnnualIncome(Double.parseDouble(txtAnnualIncome.getText()));
        request.setLiabilies(Double.parseDouble(txtLiabilities.getText()));
        request.setSavings(Double.parseDouble(txtSavings.getText()));
        request.setPartner(txtPartner.getText());
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof LegalDepartmentOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Form Submitted successfully");
        }
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter the data correcctly");
        }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagementWorkAreaJPanel dwajp = (ManagementWorkAreaJPanel) component;
        dwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAnnualIncome;
    private javax.swing.JTextField txtChildName;
    private javax.swing.JTextField txtEthnicity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLiabilities;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPartner;
    private javax.swing.JPasswordField txtSSN;
    private javax.swing.JTextField txtSavings;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtsex;
    // End of variables declaration//GEN-END:variables
}
