/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagementRole;

import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.LegalDepartmentOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class FosterParentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FosterParentJPanel
     */
    JPanel userProcessContainer;
    LabTestWorkRequest request;
    Enterprise enterprise;

    FosterParentJPanel(JPanel userProcessContainer, LabTestWorkRequest request, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.enterprise = enterprise;
        populateFields();
    }
    
    public void populateFields(){
        txtChildName.setText(request.getChildName());//Child Name is fetched
        txtChildGender.setText(request.getSex());//Child Gender is fetched
        txtEthnicity.setText(request.getEthnicity());// Child Ethinicity is fetched
        ImageIcon imageIcon = new ImageIcon(request.getImagePath());
        lblImage.setIcon(imageIcon);// Child Image is fetched
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtProfession = new javax.swing.JTextField();
        lblProfession = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtSSN = new javax.swing.JPasswordField();
        lblSSN = new javax.swing.JLabel();
        lblAnnualIncome = new javax.swing.JLabel();
        txtAnnualIncome = new javax.swing.JTextField();
        lblLiabilities = new javax.swing.JLabel();
        txtLiabilities = new javax.swing.JTextField();
        txtPartner = new javax.swing.JTextField();
        lblPartner = new javax.swing.JLabel();
        lblSavings = new javax.swing.JLabel();
        txtSavings = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtChildName = new javax.swing.JTextField();
        txtChildGender = new javax.swing.JTextField();
        txtEthnicity = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtGender = new javax.swing.JTextField();

        jLabel4.setText("Age");

        jLabel6.setText("Occupation");

        jLabel15.setText("Sex");

        setBackground(new java.awt.Color(177, 201, 226));
        setLayout(null);

        txtFirstName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtFirstName);
        txtFirstName.setBounds(699, 205, 250, 27);

        lblFirstName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblFirstName.setText("First Name:");
        add(lblFirstName);
        lblFirstName.setBounds(554, 210, 100, 21);

        txtLastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtLastName);
        txtLastName.setBounds(700, 250, 250, 27);

        lblLastName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLastName.setText("Last Name:");
        add(lblLastName);
        lblLastName.setBounds(563, 255, 110, 21);

        txtAge.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtAge);
        txtAge.setBounds(700, 290, 60, 27);

        lblAge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAge.setText("Age:");
        add(lblAge);
        lblAge.setBounds(610, 290, 40, 30);

        txtProfession.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtProfession);
        txtProfession.setBounds(700, 370, 250, 27);

        lblProfession.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProfession.setText("Profession:");
        add(lblProfession);
        lblProfession.setBounds(564, 370, 90, 30);

        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGender.setText("Gender:");
        add(lblGender);
        lblGender.setBounds(586, 330, 70, 20);

        txtSSN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });
        add(txtSSN);
        txtSSN.setBounds(700, 410, 250, 27);

        lblSSN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSSN.setText("Social Security Number:");
        add(lblSSN);
        lblSSN.setBounds(459, 407, 200, 30);

        lblAnnualIncome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAnnualIncome.setText("Annual Income ($):");
        add(lblAnnualIncome);
        lblAnnualIncome.setBounds(501, 450, 190, 30);

        txtAnnualIncome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAnnualIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnnualIncomeActionPerformed(evt);
            }
        });
        add(txtAnnualIncome);
        txtAnnualIncome.setBounds(700, 450, 250, 27);

        lblLiabilities.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLiabilities.setText("Liabilities if Any ($):");
        add(lblLiabilities);
        lblLiabilities.setBounds(490, 490, 170, 30);

        txtLiabilities.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtLiabilities);
        txtLiabilities.setBounds(700, 490, 250, 27);

        txtPartner.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartnerActionPerformed(evt);
            }
        });
        add(txtPartner);
        txtPartner.setBounds(700, 530, 250, 27);

        lblPartner.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPartner.setText("Spouse / Partner's full Name:");
        add(lblPartner);
        lblPartner.setBounds(416, 530, 260, 30);

        lblSavings.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSavings.setText("Savings / FD's /Shares if Any ($):");
        add(lblSavings);
        lblSavings.setBounds(394, 580, 270, 30);

        txtSavings.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtSavings);
        txtSavings.setBounds(700, 580, 250, 27);

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(590, 640, 176, 40);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Child Name:");
        add(jLabel13);
        jLabel13.setBounds(46, 225, 110, 21);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Child Gender:");
        add(jLabel14);
        jLabel14.setBounds(38, 270, 120, 21);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Ethnicity:");
        add(jLabel16);
        jLabel16.setBounds(81, 315, 90, 21);

        txtChildName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtChildName);
        txtChildName.setBounds(193, 220, 200, 27);

        txtChildGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtChildGender);
        txtChildGender.setBounds(193, 265, 98, 27);

        txtEthnicity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtEthnicity);
        txtEthnicity.setBounds(193, 310, 200, 27);

        lblImage.setText(".");
        add(lblImage);
        lblImage.setBounds(40, 380, 380, 330);

        lblHeader.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHeader.setText("Enter Guardian details");
        add(lblHeader);
        lblHeader.setBounds(420, 90, 237, 29);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(28, 27, 72, 37);

        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtGender);
        txtGender.setBounds(700, 330, 64, 27);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartnerActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String ssnval = "^\\d{10}";
        Pattern pat3 = Pattern.compile(ssnval);
        Matcher mat3 = pat3.matcher(txtSSN.getText());
        if(!mat3.matches()){
        JOptionPane.showMessageDialog(null, "Invalid SSN");
        }
        else if(txtFirstName.getText()==null||txtFirstName.getText().isEmpty()||txtLastName.getText()==null||txtLastName.getText().isEmpty()||txtAge.getText()==null||txtAge.getText().isEmpty()||txtChildGender.getText()==null||txtChildGender.getText().isEmpty()||txtProfession.getText()==null||txtProfession.getText().isEmpty()||txtSSN.getText()==null||txtSSN.getText().isEmpty()||txtAnnualIncome.getText()==null||txtAnnualIncome.getText().isEmpty())
        {
                        JOptionPane.showMessageDialog(null, "One or more mandatory text fields might be empty");

        }
        else{
            try{
        request.setParent(txtFirstName.getText()+" "+txtLastName.getText());
        request.setAge(Integer.parseInt(txtAge.getText()));
        request.setParentsex((String)(txtGender.getText()));
        request.setOccupation(txtProfession.getText());
        request.setSSN(Double.parseDouble(txtSSN.getText()));
        request.setAnnualIncome(Double.parseDouble(txtAnnualIncome.getText()));
        request.setLiabilies(Double.parseDouble(txtLiabilities.getText()));
        request.setSavings(Double.parseDouble(txtSavings.getText()));
        request.setPartner(txtPartner.getText());
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof LegalDepartmentOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Form Submitted successfully");
        }
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter the data correcctly");
        }
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagementWorkAreaJPanel dwajp = (ManagementWorkAreaJPanel) component;
        dwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtAnnualIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnnualIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnnualIncomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAnnualIncome;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLiabilities;
    private javax.swing.JLabel lblPartner;
    private javax.swing.JLabel lblProfession;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSavings;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAnnualIncome;
    private javax.swing.JTextField txtChildGender;
    private javax.swing.JTextField txtChildName;
    private javax.swing.JTextField txtEthnicity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLiabilities;
    private javax.swing.JTextField txtPartner;
    private javax.swing.JTextField txtProfession;
    private javax.swing.JPasswordField txtSSN;
    private javax.swing.JTextField txtSavings;
    // End of variables declaration//GEN-END:variables
}
