/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagementRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LegalDepartmentOrganization;
import Business.Organization.ManagementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.DoctorRole.ViewPatientDetailsJPanel;

/**
 *
 * 
 */
public class ManagementWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    ManagementOrganization organization;
    Enterprise enterprise;
    EcoSystem system;
    /**
     * Creates new form ManagementWorkAreaJPanel
     */

    public ManagementWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, ManagementOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        populateTable();
        Icon i = lblBG.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(lblBG.getWidth() , lblBG.getHeight(), Image.SCALE_SMOOTH);
        lblBG.setIcon(new ImageIcon(image));
    }

     public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) requestTable.getModel();
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getParent();
            row[2] = request.getLawyer();
            if(request.getApproval()==null){
                row[3] = "";
            }
            else{
            row[3] = request.getApproval()==Boolean.TRUE? "Approved":"Disapproved";
            }
            model.addRow(row);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        btnManageDonations = new javax.swing.JButton();
        lblBG = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        requestTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Child Name", "Foster Parent", "Lawyer", "Status"
            }
        ));
        jScrollPane1.setViewportView(requestTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(279, 102, 618, 321);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Click ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(453, 509, 76, 35);

        lblHeader.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblHeader.setText("To Submit Foster Parent Form for the Selected Child");
        add(lblHeader);
        lblHeader.setBounds(305, 456, 450, 35);

        btnManageDonations.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnManageDonations.setText("Manage Donations");
        btnManageDonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDonationsActionPerformed(evt);
            }
        });
        add(btnManageDonations);
        btnManageDonations.setBounds(407, 574, 193, 47);

        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/management.jpg"))); // NOI18N
        add(lblBG);
        lblBG.setBounds(0, 0, 1800, 1201);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = requestTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        LabTestWorkRequest request = (LabTestWorkRequest)requestTable.getValueAt(selectedRow, 0);
     
        
        FosterParentJPanel processWorkRequestJPanel = new FosterParentJPanel(userProcessContainer, request, enterprise);
        userProcessContainer.add("FosterParentJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnManageDonationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDonationsActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageDonationsJPanel", new ManageDonationsJPanel(userProcessContainer, userAccount, enterprise,system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDonationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDonations;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTable requestTable;
    // End of variables declaration//GEN-END:variables
}
