/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagementRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.BankManagerOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.DoctorRole.DoctorWorkAreaJPanel;

/**
 *
 * 
 */
public class ManageDonationsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDonationsJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Enterprise enterprise;
    EcoSystem system;
    Network NET;

    ManageDonationsJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userAccount=userAccount;
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.system=system;
        txtBankBalance.setText(WorkRequest.getBankbalance()+"");
        txtHighestDonor.setText(WorkRequest.getHighestdonor());
        populateFields();
    }

    public void populateFields(){
        DefaultTableModel model = (DefaultTableModel) tbldonation.getModel();
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request.getBankapproval()=="Approved"){
            Object[] row = new Object[3];
            row[0] = request;
            row[1] = request.getBankapproval()==null||request.getBankapproval().isEmpty()?"Pending":"Approved";
            model.addRow(row);
            }
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBankBalance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblDonationAmount = new javax.swing.JLabel();
        txtDonationAmount = new javax.swing.JTextField();
        lblPeronalMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPersonalMessage = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtHighestDonor = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldonation = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 102, 204));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(null);

        txtBankBalance.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBankBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankBalanceActionPerformed(evt);
            }
        });
        add(txtBankBalance);
        txtBankBalance.setBounds(732, 395, 200, 23);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Bank Account Balance:");
        add(jLabel1);
        jLabel1.setBounds(506, 395, 200, 21);

        lblFirstName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblFirstName.setText("First Name:");
        add(lblFirstName);
        lblFirstName.setBounds(78, 100, 100, 21);

        txtFirstName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtFirstName);
        txtFirstName.setBounds(240, 100, 234, 23);

        lblLastName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLastName.setText("Last Name:");
        add(lblLastName);
        lblLastName.setBounds(79, 141, 100, 21);

        txtLastName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtLastName);
        txtLastName.setBounds(240, 141, 234, 23);

        lblDonationAmount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDonationAmount.setText("Donation Amount:");
        add(lblDonationAmount);
        lblDonationAmount.setBounds(21, 182, 160, 21);

        txtDonationAmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtDonationAmount);
        txtDonationAmount.setBounds(240, 182, 234, 23);

        lblPeronalMessage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPeronalMessage.setText("Personal Message:");
        add(lblPeronalMessage);
        lblPeronalMessage.setBounds(16, 262, 160, 21);

        txtPersonalMessage.setColumns(20);
        txtPersonalMessage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPersonalMessage.setRows(5);
        jScrollPane1.setViewportView(txtPersonalMessage);

        add(jScrollPane1);
        jScrollPane1.setBounds(240, 231, 234, 91);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Highest Donor:");
        add(jLabel6);
        jLabel6.setBounds(570, 446, 140, 21);

        txtHighestDonor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtHighestDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHighestDonorActionPerformed(evt);
            }
        });
        add(txtHighestDonor);
        txtHighestDonor.setBounds(732, 446, 200, 23);

        btnConfirm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        add(btnConfirm);
        btnConfirm.setBounds(89, 384, 176, 44);

        tbldonation.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbldonation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor Name", "Donation Amount "
            }
        ));
        jScrollPane2.setViewportView(tbldonation);

        add(jScrollPane2);
        jScrollPane2.setBounds(538, 93, 423, 229);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBankBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankBalanceActionPerformed

    private void txtHighestDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHighestDonorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHighestDonorActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        try{
            if(txtFirstName.getText()==null||txtFirstName.getText().isEmpty()||txtLastName.getText()==null||txtLastName.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "One or more text fields might be empty");
            }else{
                    LabTestWorkRequest request = new LabTestWorkRequest();
                    request.setChildName(txtFirstName.getText()+" "+txtLastName.getText());
                    request.setDonationamount(Double.parseDouble(txtDonationAmount.getText()));
                    request.setDonormessage(txtPersonalMessage.getText());
Organization org = null;
        
        for(Network network: system.getNetworkList()){
            for(Enterprise ent:network.getEnterpriseDirectory().getEnterpriseList()){
                if(ent==enterprise){
                    NET=network;
                }
            }
        }
            for(Enterprise ent:NET.getEnterpriseDirectory().getEnterpriseList()){
                for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
                   if (organization instanceof BankManagerOrganization){
                    org = organization;
                    break;
            }
        }
            }

        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            system.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "The Payment has been sent to the Bank for Approval");
        populateFields();
        }}catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please check your Inputs");
        }
    }//GEN-LAST:event_btnConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDonationAmount;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPeronalMessage;
    private javax.swing.JTable tbldonation;
    private javax.swing.JTextField txtBankBalance;
    private javax.swing.JTextField txtDonationAmount;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHighestDonor;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextArea txtPersonalMessage;
    // End of variables declaration//GEN-END:variables
}
