/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OfficialRole;

import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class ReportSummary extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    LabTestWorkRequest request;
    /**
     * Creates new form ReportSummary
     */
   

    ReportSummary(JPanel userProcessContainer, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        populateFields();
    }
    
    public void populateFields(){
        txtName.setText(request.getReceiver()+"");
        txtSummaryReport.setText(request.getReport());
        txtChildName.setText(request.getChildName());
        txtGender.setText(request.getSex());
        txtChildEthnicity.setText(request.getEthnicity());
        txtWhen.setText(request.getWhenFound());
        txtChildWhere.setText(request.getWhereFound());
        txtDesc.setText(request.getDescribe());
        ImageIcon imageIcon = new ImageIcon(request.getImagePath());
        lblImg.setIcon(imageIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spReportSummarry = new javax.swing.JScrollPane();
        txtSummaryReport = new javax.swing.JTextArea();
        lblReportSummary = new javax.swing.JLabel();
        lblInvestigatorName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        spWhere = new javax.swing.JScrollPane();
        txtChildWhere = new javax.swing.JTextArea();
        lblWhen = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        spDesc = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        txtChildName = new javax.swing.JTextField();
        lblWhere = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtChildEthnicity = new javax.swing.JTextField();
        txtWhen = new javax.swing.JTextField();
        lblEthnicity = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(177, 201, 226));
        setLayout(null);

        txtSummaryReport.setColumns(20);
        txtSummaryReport.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSummaryReport.setRows(5);
        spReportSummarry.setViewportView(txtSummaryReport);

        add(spReportSummarry);
        spReportSummarry.setBounds(860, 580, 260, 119);

        lblReportSummary.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblReportSummary.setText("Report Summary:");
        add(lblReportSummary);
        lblReportSummary.setBounds(700, 610, 170, 40);

        lblInvestigatorName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblInvestigatorName.setText("Investigator Name:");
        add(lblInvestigatorName);
        lblInvestigatorName.setBounds(690, 530, 180, 30);

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtName);
        txtName.setBounds(860, 530, 260, 30);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(39, 35, 72, 37);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Child Name:");
        lblName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblName);
        lblName.setBounds(30, 120, 170, 30);

        txtChildWhere.setColumns(20);
        txtChildWhere.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtChildWhere.setRows(5);
        spWhere.setViewportView(txtChildWhere);

        add(spWhere);
        spWhere.setBounds(320, 300, 220, 91);

        lblWhen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblWhen.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWhen.setText("When was the Child found:");
        lblWhen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblWhen);
        lblWhen.setBounds(50, 210, 250, 40);

        lblDesc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDesc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDesc.setText("Description of the Incident:");
        lblDesc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblDesc);
        lblDesc.setBounds(80, 477, 240, 30);

        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDesc.setRows(5);
        spDesc.setViewportView(txtDesc);

        add(spDesc);
        spDesc.setBounds(330, 450, 215, 98);

        txtChildName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtChildName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChildNameActionPerformed(evt);
            }
        });
        add(txtChildName);
        txtChildName.setBounds(210, 120, 215, 30);

        lblWhere.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblWhere.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWhere.setText("Where was the Child found:");
        lblWhere.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblWhere);
        lblWhere.setBounds(60, 320, 250, 40);

        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender);
        txtGender.setBounds(520, 120, 215, 30);

        txtChildEthnicity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtChildEthnicity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChildEthnicityActionPerformed(evt);
            }
        });
        add(txtChildEthnicity);
        txtChildEthnicity.setBounds(850, 123, 215, 30);

        txtWhen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtWhen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWhenActionPerformed(evt);
            }
        });
        add(txtWhen);
        txtWhen.setBounds(310, 210, 230, 30);

        lblEthnicity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblEthnicity.setText("Ethnicity:");
        add(lblEthnicity);
        lblEthnicity.setBounds(760, 120, 100, 30);

        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGender.setText("Gender:");
        add(lblGender);
        lblGender.setBounds(440, 120, 90, 30);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/report-2.jpg"))); // NOI18N
        lblImg.setMaximumSize(new java.awt.Dimension(1000, 1000));
        lblImg.setMinimumSize(new java.awt.Dimension(1000, 1000));
        lblImg.setPreferredSize(new java.awt.Dimension(1000, 1000));
        add(lblImg);
        lblImg.setBounds(-580, -50, 2470, 1660);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        OfficialWorkAreaJPanel owap = (OfficialWorkAreaJPanel) component;
        owap.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtChildEthnicityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChildEthnicityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChildEthnicityActionPerformed

    private void txtWhenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWhenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWhenActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtChildNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChildNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChildNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblEthnicity;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblInvestigatorName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblReportSummary;
    private javax.swing.JLabel lblWhen;
    private javax.swing.JLabel lblWhere;
    private javax.swing.JScrollPane spDesc;
    private javax.swing.JScrollPane spReportSummarry;
    private javax.swing.JScrollPane spWhere;
    private javax.swing.JTextField txtChildEthnicity;
    private javax.swing.JTextField txtChildName;
    private javax.swing.JTextArea txtChildWhere;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtSummaryReport;
    private javax.swing.JTextField txtWhen;
    // End of variables declaration//GEN-END:variables
}
