/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OfficialRole;

import Buisness.IntegerVerifier;
import Buisness.StringVerifier;
import Business.Enterprise.Enterprise;
import Business.Organization.PoliceDepartmentOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InvestigationWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.File;
import javax.swing.InputVerifier;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class RequestInvestigationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    JFileChooser image;
    /**
     * Creates new form RequestInvestigationJPanel
     */
    
    RequestInvestigationJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise) {
        initComponents();  
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        valueLabel1.setText(enterprise.getName());
        image=new JFileChooser();
        addVerifiers();
    }
    
    private void addVerifiers(){
   
    InputVerifier stringVerifier = new StringVerifier();
    txtName.setInputVerifier(stringVerifier);
    txtGender.setInputVerifier(stringVerifier);
    txtChildEthnicity.setInputVerifier(stringVerifier);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblWhere = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblEthnicity = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtChildEthnicity = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        spWhere = new javax.swing.JScrollPane();
        txtFoundWhere = new javax.swing.JTextArea();
        spDetails = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        btnReq = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        spDesc = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        lblDetails = new javax.swing.JLabel();
        valueLabel1 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(177, 201, 226));
        setLayout(null);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Child Name:");
        lblName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblName);
        lblName.setBounds(40, 100, 160, 30);

        lblWhere.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblWhere.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWhere.setText("Where was the Child found:");
        lblWhere.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblWhere);
        lblWhere.setBounds(120, 270, 270, 30);

        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGender.setText("Gender:");
        add(lblGender);
        lblGender.setBounds(480, 100, 90, 30);

        lblEthnicity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblEthnicity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEthnicity.setText("Ethnicity:");
        lblEthnicity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblEthnicity);
        lblEthnicity.setBounds(770, 100, 110, 30);

        lblDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDate.setText("When was the Child found (MM/DD/YYYY):");
        lblDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblDate);
        lblDate.setBounds(-10, 170, 410, 40);

        lblDesc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDesc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDesc.setText("Describe the Incident:");
        lblDesc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblDesc);
        lblDesc.setBounds(140, 440, 240, 30);

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtName);
        txtName.setBounds(210, 100, 250, 30);

        txtChildEthnicity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtChildEthnicity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChildEthnicityActionPerformed(evt);
            }
        });
        add(txtChildEthnicity);
        txtChildEthnicity.setBounds(880, 100, 250, 30);

        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        add(txtDate);
        txtDate.setBounds(410, 180, 250, 30);

        txtFoundWhere.setColumns(20);
        txtFoundWhere.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtFoundWhere.setRows(5);
        spWhere.setViewportView(txtFoundWhere);

        add(spWhere);
        spWhere.setBounds(410, 240, 250, 115);

        txtDetails.setColumns(20);
        txtDetails.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDetails.setRows(5);
        spDetails.setViewportView(txtDetails);

        add(spDetails);
        spDetails.setBounds(410, 530, 250, 115);

        btnReq.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReq.setText("Request Investigation");
        btnReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqActionPerformed(evt);
            }
        });
        add(btnReq);
        btnReq.setBounds(650, 710, 211, 40);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(34, 29, 77, 33);

        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDesc.setRows(5);
        spDesc.setViewportView(txtDesc);

        add(spDesc);
        spDesc.setBounds(410, 390, 250, 115);

        lblDetails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDetails.setText("Details of Parents / Guardians if Any:");
        add(lblDetails);
        lblDetails.setBounds(90, 560, 300, 40);

        valueLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        valueLabel1.setText("<value>");
        add(valueLabel1);
        valueLabel1.setBounds(480, 30, 292, 29);

        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtGender);
        txtGender.setBounds(580, 100, 160, 30);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/police_03.jpg"))); // NOI18N
        lblImg.setMaximumSize(new java.awt.Dimension(800, 800));
        lblImg.setMinimumSize(new java.awt.Dimension(800, 800));
        lblImg.setPreferredSize(new java.awt.Dimension(800, 800));
        add(lblImg);
        lblImg.setBounds(-1510, -30, 3140, 1930);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtChildEthnicityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChildEthnicityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChildEthnicityActionPerformed

    private void btnReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqActionPerformed
        // TODO add your handling code here:
        try{
        String[] valid = txtDate.getText().split("/");
        if(Integer.parseInt(valid[0])==0 || Integer.parseInt(valid[0])>12 || Integer.parseInt(valid[1])==0 ||Integer.parseInt(valid[1])>31 || Integer.parseInt(valid[2])<1000 || Integer.parseInt(valid[2])>2021){
            JOptionPane.showMessageDialog(null, "Incorrect Date format");
        }else{
        if(txtName.getText()==null || txtName.getText().isEmpty() || txtChildEthnicity.getText()==null || txtChildEthnicity.getText().isEmpty() ||  txtDate.getText()==null || txtDate.getText().isEmpty() || txtFoundWhere.getText()==null || txtFoundWhere.getText().isEmpty() ||  txtDesc.getText()==null || txtDesc.getText().isEmpty() || txtDetails.getText().isEmpty() ||  txtDetails.getText()==null)
        {
            JOptionPane.showMessageDialog(null, "One or more text fields might be empty");

        }
        /*
        else if(cbGender.getSelectedItem()=="Select Sex"){
                        JOptionPane.showMessageDialog(null, "Please select a Sex");

        }*/
        else{
            LabTestWorkRequest request = new LabTestWorkRequest();

            request.setSender(userAccount);
            request.setStatus("Report  Filed");
            request.setChildName(txtName.getText());
            request.setSex((String)txtGender.getText());
            request.setEthnicity(txtChildEthnicity.getText());
            request.setWhenFound(txtDate.getText());
            request.setWhereFound(txtFoundWhere.getText());
            request.setDescribe(txtDesc.getText());
            request.setParentDetails(txtDetails.getText());
                    
            JOptionPane.showMessageDialog(null, "Please provide a Photo of the Child");
    int returnVal= image.showOpenDialog(RequestInvestigationJPanel.this);
    if(returnVal == JFileChooser.APPROVE_OPTION)
    { File file = image.getSelectedFile();
    String imagePath= file.getAbsolutePath();
    request.setImagePath(imagePath);}
    
        if(request.getImagePath() == null || request.getImagePath().isEmpty()){
            JOptionPane.showMessageDialog(null, "Photo not found. Please Reupload");

        }
        else{
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PoliceDepartmentOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Report Filed Successfully");
                }}}}catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Incorrect date format");
                }
        
        
    txtChildEthnicity.setText("");
    txtDate.setText("");
    txtDesc.setText("");
    txtDetails.setText("");
    txtFoundWhere.setText("");
    txtGender.setText("");
    txtName.setText("");
        
        
    }//GEN-LAST:event_btnReqActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        OfficialWorkAreaJPanel owap = (OfficialWorkAreaJPanel) component;
        owap.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReq;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblEthnicity;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblWhere;
    private javax.swing.JScrollPane spDesc;
    private javax.swing.JScrollPane spDetails;
    private javax.swing.JScrollPane spWhere;
    private javax.swing.JTextField txtChildEthnicity;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextArea txtDetails;
    private javax.swing.JTextArea txtFoundWhere;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel valueLabel1;
    // End of variables declaration//GEN-END:variables
}
