/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OfficialRole;

import Buisness.StringVerifier;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PoliceDepartmentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 *
 */
public class RequestMedicalExaminationJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    LabTestWorkRequest request;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private Network NET;
    /**
     * Creates new form RequestMedicalExaminationJPanel
     */
    
    RequestMedicalExaminationJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, LabTestWorkRequest request, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system = system;
        populatefields();
        addVerifiers();
    }
    
    private void addVerifiers(){
   
    InputVerifier stringVerifier = new StringVerifier();
    txtName.setInputVerifier(stringVerifier);
    txtGender.setInputVerifier(stringVerifier);
    }

    public void populatefields(){
        txtName.setText(request.getChildName());
        txtGender.setText(request.getSex());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGender = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblMedicalIssues = new javax.swing.JLabel();
        spMedicalIssues = new javax.swing.JScrollPane();
        txtMedicalIssue = new javax.swing.JTextArea();
        btnRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(177, 201, 226));
        setLayout(null);

        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGender.setText("Gender:");
        add(lblGender);
        lblGender.setBounds(462, 148, 106, 29);

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtName);
        txtName.setBounds(212, 152, 226, 27);

        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtGender);
        txtGender.setBounds(586, 152, 226, 27);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Child Name:");
        lblName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblName);
        lblName.setBounds(35, 148, 159, 29);

        lblMedicalIssues.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMedicalIssues.setText("Medical issues if Any:");
        add(lblMedicalIssues);
        lblMedicalIssues.setBounds(170, 230, 190, 34);

        txtMedicalIssue.setColumns(20);
        txtMedicalIssue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMedicalIssue.setRows(5);
        spMedicalIssues.setViewportView(txtMedicalIssue);

        add(spMedicalIssues);
        spMedicalIssues.setBounds(363, 210, 449, 111);

        btnRequest.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRequest.setText("Request Examination");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest);
        btnRequest.setBounds(233, 387, 325, 50);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(41, 32, 72, 38);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/medical-work-area.png"))); // NOI18N
        lblImg.setMaximumSize(new java.awt.Dimension(1000, 1000));
        lblImg.setMinimumSize(new java.awt.Dimension(1000, 1000));
        lblImg.setPreferredSize(new java.awt.Dimension(1000, 1000));
        add(lblImg);
        lblImg.setBounds(200, 30, 1800, 750);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        request.setKnownIssues(txtMedicalIssue.getText());
        request.setMedicalStatus("Pending");

        Organization org = null;
        
        for(Network network: system.getNetworkList()){
            for(Enterprise ent:network.getEnterpriseDirectory().getEnterpriseList()){
                if(ent==enterprise){
                    NET=network;
                }
            }
        }
            for(Enterprise ent:NET.getEnterpriseDirectory().getEnterpriseList()){
                for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
                   if (organization instanceof DoctorOrganization){
                    org = organization;
                    break;
            }
        }
            }

        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            system.getWorkQueue().getWorkRequestList().add(request);
        }
            JOptionPane.showMessageDialog(null, "Medical Examination Requested Successfully");
            
 txtName.setText("");
 txtGender.setText("");
 txtMedicalIssue.setText("");

    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
                userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        OfficialWorkAreaJPanel owap = (OfficialWorkAreaJPanel) component;
        owap.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblMedicalIssues;
    private javax.swing.JLabel lblName;
    private javax.swing.JScrollPane spMedicalIssues;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextArea txtMedicalIssue;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
