/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LawyerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LegalDepartmentOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.OfficialRole.ReportSummary;

/**
 *
 *
 */
public class LawyerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    LegalDepartmentOrganization organization;
    Enterprise enterprise;
    EcoSystem system;
    /**
     * Creates new form LawyerWorkAreaJPanel
     */

    public LawyerWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, LegalDepartmentOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system; 
        populateFields();
        Icon i = lblBG.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(lblBG.getWidth() , lblBG.getHeight(), Image.SCALE_SMOOTH);
        lblBG.setIcon(new ImageIcon(image));
    }
    
        public void populateFields(){
          DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getParent();
            row[2] = request.getLawyer();
            if(request.getApproval()==null){
                row[3] = "Pending";
            }
            else{
            row[3] = request.getApproval()==Boolean.TRUE? "Approved":"Disapproved";
            }
            model.addRow(row);
            
    }
    }   
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        btnClick = new javax.swing.JButton();
        lblClick = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(2000, 1333));
        setLayout(null);

        tblRequest.setBackground(new java.awt.Color(221, 221, 221));
        tblRequest.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Child Name", "Foster Parent", "Lawyer", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblRequest);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 630, 340);

        btnClick.setBackground(new java.awt.Color(221, 221, 221));
        btnClick.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClick.setText("Click here");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });
        add(btnClick);
        btnClick.setBounds(40, 390, 120, 28);

        lblClick.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblClick.setForeground(new java.awt.Color(255, 255, 255));
        lblClick.setText("To View Selected Foster Parent Document");
        add(lblClick);
        lblClick.setBounds(180, 390, 370, 24);

        lblBG.setForeground(new java.awt.Color(0, 0, 51));
        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lawyer.jpg"))); // NOI18N
        lblBG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBG.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(lblBG);
        lblBG.setBounds(0, 0, 2000, 1333);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        LabTestWorkRequest request = (LabTestWorkRequest)tblRequest.getValueAt(selectedRow, 0);
        
        ViewFosterParentDocument processWorkRequestJPanel = new ViewFosterParentDocument(userProcessContainer, request, userAccount);
        userProcessContainer.add("ViewFosterParentDocument", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnClickActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClick;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblClick;
    private javax.swing.JTable tblRequest;
    // End of variables declaration//GEN-END:variables
}
