/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LawyerRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class ViewFosterParentDocument extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest request;
    UserAccount userAccount;
    /**
     * Creates new form ViewFosterParentDocument
     */


    ViewFosterParentDocument(JPanel userProcessContainer, LabTestWorkRequest request, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        this.userAccount=userAccount;
        populatefields();    }
    
        public void populatefields(){
        txtChildName.setText(request.getChildName());
        txtChildGender.setText(request.getSex());
        txtEthnicity.setText(request.getEthnicity());
        ImageIcon imageIcon = new ImageIcon(request.getImagePath());
        lblImage.setIcon(imageIcon);
        txtName.setText(request.getParent());
        txtAge.setText(request.getAge()+"");
        txtGender.setText(request.getParentsex());
        txtProfession.setText(request.getOccupation());
        txtSSN.setText(request.getSSN()+"");
        txtAnnualIncome.setText(request.getAnnualIncome()+"");
        txtLiabilities.setText(request.getLiabilies()+"");
        txtPartner.setText(request.getPartner());
        txtSavings.setText(request.getSavings()+"");
                
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSavings = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProfession = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtChildName = new javax.swing.JTextField();
        txtAnnualIncome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtChildGender = new javax.swing.JTextField();
        txtLiabilities = new javax.swing.JTextField();
        txtEthnicity = new javax.swing.JTextField();
        txtPartner = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        btnApproval = new javax.swing.JToggleButton();
        btnSubmit = new javax.swing.JButton();
        btnDisapproval = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 204));
        setLayout(null);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Spouse / Partner's full Name:");
        add(jLabel11);
        jLabel11.setBounds(536, 387, 290, 30);

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtName);
        txtName.setBounds(840, 110, 250, 27);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Savings / FD's /Shares if Any ($):");
        add(jLabel12);
        jLabel12.setBounds(514, 427, 320, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText(" Name:");
        add(jLabel2);
        jLabel2.setBounds(710, 110, 70, 30);

        txtSavings.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtSavings);
        txtSavings.setBounds(840, 430, 250, 27);

        txtAge.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtAge);
        txtAge.setBounds(840, 150, 80, 27);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Age:");
        add(jLabel3);
        jLabel3.setBounds(728, 150, 50, 30);

        txtProfession.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtProfession);
        txtProfession.setBounds(840, 230, 250, 27);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Profession:");
        add(jLabel5);
        jLabel5.setBounds(676, 227, 110, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Child Name:");
        add(jLabel13);
        jLabel13.setBounds(40, 200, 120, 21);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Child Gender:");
        add(jLabel14);
        jLabel14.setBounds(31, 248, 120, 21);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Ethnicity:");
        add(jLabel16);
        jLabel16.setBounds(70, 290, 90, 21);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Gender:");
        add(jLabel7);
        jLabel7.setBounds(697, 190, 80, 30);

        txtSSN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtSSN);
        txtSSN.setBounds(840, 270, 250, 27);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Social Security Number:");
        add(jLabel8);
        jLabel8.setBounds(570, 270, 220, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Annual Income ($):");
        add(jLabel9);
        jLabel9.setBounds(611, 310, 200, 20);

        txtChildName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtChildName);
        txtChildName.setBounds(177, 198, 200, 27);

        txtAnnualIncome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtAnnualIncome);
        txtAnnualIncome.setBounds(840, 310, 250, 27);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Liabilities if Any ($):");
        add(jLabel10);
        jLabel10.setBounds(611, 350, 200, 30);

        txtChildGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtChildGender);
        txtChildGender.setBounds(177, 243, 200, 27);

        txtLiabilities.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtLiabilities);
        txtLiabilities.setBounds(840, 350, 250, 27);

        txtEthnicity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtEthnicity);
        txtEthnicity.setBounds(177, 288, 200, 27);

        txtPartner.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartnerActionPerformed(evt);
            }
        });
        add(txtPartner);
        txtPartner.setBounds(840, 390, 250, 27);

        lblImage.setText(".");
        add(lblImage);
        lblImage.setBounds(50, 380, 390, 320);

        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtGender);
        txtGender.setBounds(840, 190, 80, 27);

        btnApproval.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnApproval.setText("Approve");
        btnApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovalActionPerformed(evt);
            }
        });
        add(btnApproval);
        btnApproval.setBounds(630, 510, 126, 50);

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(760, 590, 124, 50);

        btnDisapproval.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDisapproval.setText("Disapprove");
        btnDisapproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisapprovalActionPerformed(evt);
            }
        });
        add(btnDisapproval);
        btnDisapproval.setBounds(880, 510, 125, 50);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(38, 22, 77, 38);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartnerActionPerformed

    private void btnApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApprovalActionPerformed

    private void btnDisapprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisapprovalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisapprovalActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(btnApproval.isSelected() && btnDisapproval.isSelected()){
            JOptionPane.showMessageDialog(null, "Please select one of the options");
        }
        else{
        if(btnApproval.isSelected()){
            request.setApproval(Boolean.TRUE);
                        JOptionPane.showMessageDialog(null, "Approved");
                        request.setLawyer(userAccount.getUsername());
        }
        else if(btnDisapproval.isSelected()){
            request.setApproval(Boolean.FALSE);
                        JOptionPane.showMessageDialog(null, "Disapproved");
                        request.setLawyer(userAccount.getUsername());

        }
        txtChildName.setText("");
        txtChildGender.setText("");
        txtEthnicity.setText("");
        txtName.setText("");
        txtAge.setText("");
        txtGender.setText("");
        txtProfession.setText("");
        txtSSN.setText("");
        txtAnnualIncome.setText("");
        txtLiabilities.setText("");
        txtSavings.setText("");
        txtPartner.setText(""); 
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LawyerWorkAreaJPanel dwajp = (LawyerWorkAreaJPanel) component;
        dwajp.populateFields();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnApproval;
    private javax.swing.JToggleButton btnDisapproval;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAnnualIncome;
    private javax.swing.JTextField txtChildGender;
    private javax.swing.JTextField txtChildName;
    private javax.swing.JTextField txtEthnicity;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLiabilities;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPartner;
    private javax.swing.JTextField txtProfession;
    private javax.swing.JPasswordField txtSSN;
    private javax.swing.JTextField txtSavings;
    // End of variables declaration//GEN-END:variables
}
