/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LawyerRole;

import Buisness.IntegerVerifier;
import Buisness.StringVerifier;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class ViewFosterParentDocument extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest request;
    UserAccount userAccount;
    /**
     * Creates new form ViewFosterParentDocument
     */


    ViewFosterParentDocument(JPanel userProcessContainer, LabTestWorkRequest request, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        this.userAccount=userAccount;
        populatefields();
        Icon i = lblBG.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(lblBG.getWidth() , lblBG.getHeight(), Image.SCALE_SMOOTH);
        lblBG.setIcon(new ImageIcon(image));
        addVerifiers();
    }
    private void addVerifiers() 
    {
        InputVerifier integerVerifier = new IntegerVerifier();
        InputVerifier stringVerifier = new StringVerifier();
        txtChildName.setInputVerifier(stringVerifier);
        txtChildGender.setInputVerifier(stringVerifier);
        txtEthnicity.setInputVerifier(stringVerifier);
        txtName.setInputVerifier(stringVerifier);
        txtAge.setInputVerifier(integerVerifier);
        txtGender.setInputVerifier(stringVerifier);
        txtProfession.setInputVerifier(stringVerifier);
        txtSSN.setInputVerifier(integerVerifier);
        txtAnnualIncome.setInputVerifier(integerVerifier);
        txtLiabilities.setInputVerifier(integerVerifier);
        txtPartner.setInputVerifier(stringVerifier);
        txtSavings.setInputVerifier(integerVerifier);    
    }
    
    
        public void populatefields(){
        txtChildName.setText(request.getChildName());
        txtChildGender.setText(request.getSex());
        txtEthnicity.setText(request.getEthnicity());
        ImageIcon imageIcon = new ImageIcon(request.getImagePath());
        lblImage.setIcon(imageIcon);
        txtName.setText(request.getParent());
        txtAge.setText(request.getAge()+"");
        txtGender.setText(request.getParentsex());
        txtProfession.setText(request.getOccupation());
        txtSSN.setText(request.getSSN()+"");
        txtAnnualIncome.setText(request.getAnnualIncome()+"");
        txtLiabilities.setText(request.getLiabilies()+"");
        txtPartner.setText(request.getPartner());
        txtSavings.setText(request.getSavings()+"");
                
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPartner = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblSavings = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtSavings = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtProfession = new javax.swing.JTextField();
        lblProfession = new javax.swing.JLabel();
        lblChildName = new javax.swing.JLabel();
        lblChildGender = new javax.swing.JLabel();
        lblEthnicity = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtSSN = new javax.swing.JPasswordField();
        lblSSN = new javax.swing.JLabel();
        lblAnnualIncome = new javax.swing.JLabel();
        txtChildName = new javax.swing.JTextField();
        txtAnnualIncome = new javax.swing.JTextField();
        lblLiabilities = new javax.swing.JLabel();
        txtChildGender = new javax.swing.JTextField();
        txtLiabilities = new javax.swing.JTextField();
        txtEthnicity = new javax.swing.JTextField();
        txtPartner = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        btnApproval = new javax.swing.JToggleButton();
        btnSubmit = new javax.swing.JButton();
        btnDisapproval = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        lblBG = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(2000, 1333));
        setLayout(null);

        lblPartner.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPartner.setForeground(new java.awt.Color(255, 255, 255));
        lblPartner.setText("Spouse / Partner's full Name:");
        add(lblPartner);
        lblPartner.setBounds(536, 387, 290, 30);

        txtName.setBackground(new java.awt.Color(249, 241, 234));
        txtName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtName);
        txtName.setBounds(840, 110, 250, 27);

        lblSavings.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSavings.setForeground(new java.awt.Color(255, 255, 255));
        lblSavings.setText("Savings / FD's /Shares if Any ($):");
        add(lblSavings);
        lblSavings.setBounds(514, 427, 320, 30);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText(" Name:");
        add(lblName);
        lblName.setBounds(710, 110, 70, 30);

        txtSavings.setBackground(new java.awt.Color(249, 241, 234));
        txtSavings.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtSavings);
        txtSavings.setBounds(840, 430, 250, 27);

        txtAge.setBackground(new java.awt.Color(249, 241, 234));
        txtAge.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtAge);
        txtAge.setBounds(840, 150, 80, 27);

        lblAge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age:");
        add(lblAge);
        lblAge.setBounds(728, 150, 50, 30);

        txtProfession.setBackground(new java.awt.Color(249, 241, 234));
        txtProfession.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtProfession);
        txtProfession.setBounds(840, 230, 250, 27);

        lblProfession.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProfession.setForeground(new java.awt.Color(255, 255, 255));
        lblProfession.setText("Profession:");
        add(lblProfession);
        lblProfession.setBounds(676, 227, 110, 30);

        lblChildName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblChildName.setForeground(new java.awt.Color(255, 255, 255));
        lblChildName.setText("Child Name:");
        add(lblChildName);
        lblChildName.setBounds(40, 200, 120, 21);

        lblChildGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblChildGender.setForeground(new java.awt.Color(255, 255, 255));
        lblChildGender.setText("Child Gender:");
        add(lblChildGender);
        lblChildGender.setBounds(31, 248, 120, 21);

        lblEthnicity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblEthnicity.setForeground(new java.awt.Color(255, 255, 255));
        lblEthnicity.setText("Ethnicity:");
        add(lblEthnicity);
        lblEthnicity.setBounds(70, 290, 90, 21);

        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setText("Gender:");
        add(lblGender);
        lblGender.setBounds(697, 190, 80, 30);

        txtSSN.setBackground(new java.awt.Color(249, 241, 234));
        txtSSN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtSSN);
        txtSSN.setBounds(840, 270, 250, 27);

        lblSSN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(255, 255, 255));
        lblSSN.setText("Social Security Number:");
        add(lblSSN);
        lblSSN.setBounds(570, 270, 220, 30);

        lblAnnualIncome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAnnualIncome.setForeground(new java.awt.Color(255, 255, 255));
        lblAnnualIncome.setText("Annual Income ($):");
        add(lblAnnualIncome);
        lblAnnualIncome.setBounds(611, 310, 200, 20);

        txtChildName.setEditable(false);
        txtChildName.setBackground(new java.awt.Color(249, 241, 234));
        txtChildName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtChildName);
        txtChildName.setBounds(177, 198, 200, 27);

        txtAnnualIncome.setBackground(new java.awt.Color(249, 241, 234));
        txtAnnualIncome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtAnnualIncome);
        txtAnnualIncome.setBounds(840, 310, 250, 27);

        lblLiabilities.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLiabilities.setForeground(new java.awt.Color(255, 255, 255));
        lblLiabilities.setText("Liabilities if Any ($):");
        add(lblLiabilities);
        lblLiabilities.setBounds(611, 350, 200, 30);

        txtChildGender.setEditable(false);
        txtChildGender.setBackground(new java.awt.Color(249, 241, 234));
        txtChildGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtChildGender);
        txtChildGender.setBounds(177, 243, 200, 27);

        txtLiabilities.setBackground(new java.awt.Color(249, 241, 234));
        txtLiabilities.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtLiabilities);
        txtLiabilities.setBounds(840, 350, 250, 27);

        txtEthnicity.setEditable(false);
        txtEthnicity.setBackground(new java.awt.Color(249, 241, 234));
        txtEthnicity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtEthnicity);
        txtEthnicity.setBounds(177, 288, 200, 27);

        txtPartner.setBackground(new java.awt.Color(249, 241, 234));
        txtPartner.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartnerActionPerformed(evt);
            }
        });
        add(txtPartner);
        txtPartner.setBounds(840, 390, 250, 27);

        lblImage.setText(".");
        add(lblImage);
        lblImage.setBounds(50, 380, 390, 320);

        txtGender.setBackground(new java.awt.Color(249, 241, 234));
        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtGender);
        txtGender.setBounds(840, 190, 80, 27);

        btnApproval.setBackground(new java.awt.Color(249, 241, 234));
        btnApproval.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnApproval.setText("Approve");
        btnApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovalActionPerformed(evt);
            }
        });
        add(btnApproval);
        btnApproval.setBounds(630, 510, 126, 50);

        btnSubmit.setBackground(new java.awt.Color(249, 241, 234));
        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(760, 590, 124, 50);

        btnDisapproval.setBackground(new java.awt.Color(249, 241, 234));
        btnDisapproval.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDisapproval.setText("Disapprove");
        btnDisapproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisapprovalActionPerformed(evt);
            }
        });
        add(btnDisapproval);
        btnDisapproval.setBounds(880, 510, 125, 50);

        jButton2.setBackground(new java.awt.Color(249, 241, 234));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("<<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(80, 20, 77, 38);

        lblBG.setForeground(new java.awt.Color(204, 204, 204));
        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/parent.jpg"))); // NOI18N
        add(lblBG);
        lblBG.setBounds(0, 0, 2000, 1333);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartnerActionPerformed

    private void btnApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApprovalActionPerformed

    private void btnDisapprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisapprovalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisapprovalActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(btnApproval.isSelected() && btnDisapproval.isSelected()){
            JOptionPane.showMessageDialog(null, "Please select one of the options");
        }
        else{
        if(btnApproval.isSelected()){
            request.setApproval(Boolean.TRUE);
                        JOptionPane.showMessageDialog(null, "Approved");
                        request.setLawyer(userAccount.getUsername());
        }
        else if(btnDisapproval.isSelected()){
            request.setApproval(Boolean.FALSE);
                        JOptionPane.showMessageDialog(null, "Disapproved");
                        request.setLawyer(userAccount.getUsername());

        }
        txtChildName.setText("");
        txtChildGender.setText("");
        txtEthnicity.setText("");
        txtName.setText("");
        txtAge.setText("");
        txtGender.setText("");
        txtProfession.setText("");
        txtSSN.setText("");
        txtAnnualIncome.setText("");
        txtLiabilities.setText("");
        txtSavings.setText("");
        txtPartner.setText(""); 
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LawyerWorkAreaJPanel dwajp = (LawyerWorkAreaJPanel) component;
        dwajp.populateFields();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnApproval;
    private javax.swing.JToggleButton btnDisapproval;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAnnualIncome;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblChildGender;
    private javax.swing.JLabel lblChildName;
    private javax.swing.JLabel lblEthnicity;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLiabilities;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPartner;
    private javax.swing.JLabel lblProfession;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSavings;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAnnualIncome;
    private javax.swing.JTextField txtChildGender;
    private javax.swing.JTextField txtChildName;
    private javax.swing.JTextField txtEthnicity;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLiabilities;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPartner;
    private javax.swing.JTextField txtProfession;
    private javax.swing.JPasswordField txtSSN;
    private javax.swing.JTextField txtSavings;
    // End of variables declaration//GEN-END:variables
}
