/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class MedicalReportJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest request;
    Organization organization;
    /**
     * Creates new form MedicalReportJPanel
     */

    MedicalReportJPanel(JPanel userProcessContainer, LabTestWorkRequest request, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.organization = organization;
        populateFields();     
    }


    public void populateFields(){
        txtName.setText(request.getChildName());
        txtGender.setText(request.getSex());
        txtTests.setText(request.getTests());
        txtTestReport.setText(request.getTestReport());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        spTestUndergone = new javax.swing.JScrollPane();
        txtTests = new javax.swing.JTextArea();
        lblTestsUndergone = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTestReport = new javax.swing.JTextArea();
        lblTestReport = new javax.swing.JLabel();
        spDoctorRemark = new javax.swing.JScrollPane();
        txtDoctorRemark = new javax.swing.JTextArea();
        lblDoctorRemark = new javax.swing.JLabel();
        btnSubmitReport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblimg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 204));
        setForeground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setLayout(null);

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName);
        txtName.setBounds(203, 139, 189, 30);

        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender);
        txtGender.setBounds(510, 139, 184, 30);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Patient Name:");
        lblName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblName);
        lblName.setBounds(65, 142, 120, 20);

        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGender.setText("Gender:");
        add(lblGender);
        lblGender.setBounds(410, 137, 82, 30);

        txtTests.setColumns(20);
        txtTests.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTests.setRows(5);
        spTestUndergone.setViewportView(txtTests);

        add(spTestUndergone);
        spTestUndergone.setBounds(410, 235, 300, 120);

        lblTestsUndergone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTestsUndergone.setForeground(new java.awt.Color(255, 255, 255));
        lblTestsUndergone.setText("  Tests Undergone:");
        add(lblTestsUndergone);
        lblTestsUndergone.setBounds(170, 290, 190, 21);

        txtTestReport.setColumns(20);
        txtTestReport.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTestReport.setRows(5);
        jScrollPane2.setViewportView(txtTestReport);

        add(jScrollPane2);
        jScrollPane2.setBounds(410, 401, 300, 120);

        lblTestReport.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTestReport.setForeground(new java.awt.Color(255, 255, 255));
        lblTestReport.setText("Test Report:");
        add(lblTestReport);
        lblTestReport.setBounds(220, 450, 140, 21);

        txtDoctorRemark.setColumns(20);
        txtDoctorRemark.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDoctorRemark.setRows(5);
        spDoctorRemark.setViewportView(txtDoctorRemark);

        add(spDoctorRemark);
        spDoctorRemark.setBounds(410, 557, 300, 120);

        lblDoctorRemark.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDoctorRemark.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorRemark.setText("Doctor's Remarks:");
        add(lblDoctorRemark);
        lblDoctorRemark.setBounds(180, 620, 170, 21);

        btnSubmitReport.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSubmitReport.setText("Submit Report");
        btnSubmitReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitReportActionPerformed(evt);
            }
        });
        add(btnSubmitReport);
        btnSubmitReport.setBounds(648, 797, 188, 56);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(47, 44, 72, 39);
        add(lblimg);
        lblimg.setBounds(20, 10, 890, 970);
    }// </editor-fold>//GEN-END:initComponents

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void btnSubmitReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitReportActionPerformed
        // TODO add your handling code here:
        if(txtDoctorRemark.getText()==null || txtDoctorRemark.getText().isEmpty())
        {
                        JOptionPane.showMessageDialog(null, "Please enter Remarks");

        }
        else{
            request.setMedicalReport(txtDoctorRemark.getText()+"\n"+"\n>>Patient examined by Dr. "+organization.getEmployeeDirectory().getEmployeeList());
                        JOptionPane.showMessageDialog(null, "Report Submitted Successfully");

        }
    }//GEN-LAST:event_btnSubmitReportActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwajp = (DoctorWorkAreaJPanel) component;
        dwajp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitReport;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDoctorRemark;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTestReport;
    private javax.swing.JLabel lblTestsUndergone;
    private javax.swing.JLabel lblimg;
    private javax.swing.JScrollPane spDoctorRemark;
    private javax.swing.JScrollPane spTestUndergone;
    private javax.swing.JTextArea txtDoctorRemark;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtTestReport;
    private javax.swing.JTextArea txtTests;
    // End of variables declaration//GEN-END:variables
}
