/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Buisness.StringVerifier;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private LabTestWorkRequest request;
    /**
     * Creates new form RequestLabTestJPanel
     */

    RequestLabTestJPanel(JPanel userProcessContainer, LabTestWorkRequest request, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;    
        this.request = request;
        populatefields();
        
        Icon i = lblImg.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(lblImg.getWidth() , lblImg.getHeight(), Image.SCALE_SMOOTH);
        lblImg.setIcon(new ImageIcon(image));
        addVerifiers();
    }
    
    private void addVerifiers(){
   
    InputVerifier stringVerifier = new StringVerifier();
    txtName.setInputVerifier(stringVerifier);
    txtGender.setInputVerifier(stringVerifier);
    
    
    }
    
    
    public void populatefields(){
        txtName.setText(request.getChildName());
        txtGender.setText(request.getSex());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequestTest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        spTest = new javax.swing.JScrollPane();
        txtTestsDone = new javax.swing.JTextArea();
        lblTestDone = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 255));
        setLayout(null);

        btnRequestTest.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRequestTest.setText("Request Test");
        btnRequestTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestTestActionPerformed(evt);
            }
        });
        add(btnRequestTest);
        btnRequestTest.setBounds(550, 280, 170, 50);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(50, 40, 72, 40);

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtName);
        txtName.setBounds(180, 180, 220, 30);

        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender);
        txtGender.setBounds(540, 180, 140, 30);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Child Name:");
        lblName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblName);
        lblName.setBounds(40, 180, 120, 30);

        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGender.setText("Gender:");
        add(lblGender);
        lblGender.setBounds(450, 180, 80, 30);

        txtTestsDone.setColumns(20);
        txtTestsDone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTestsDone.setRows(5);
        spTest.setViewportView(txtTestsDone);

        add(spTest);
        spTest.setBounds(200, 260, 290, 90);

        lblTestDone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTestDone.setText("  Tests to be Done:");
        add(lblTestDone);
        lblTestDone.setBounds(30, 290, 160, 20);

        lblImg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lab-assistant.png"))); // NOI18N
        lblImg.setMaximumSize(new java.awt.Dimension(1680, 1050));
        lblImg.setPreferredSize(new java.awt.Dimension(1680, 1050));
        add(lblImg);
        lblImg.setBounds(-10, -200, 1680, 1050);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestTestActionPerformed
        if(txtTestsDone.getText()==null || txtTestsDone.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter the Tests to be done");
        }
        else{
        request.setTests(txtTestsDone.getText());
        request.setDoctor(userAccount);
        request.setMedicalStatus("Ongoing");
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof LabOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request successfully sent");
        }
        }
        
        txtName.setText("");
        txtGender.setText("");
        txtTestsDone.setText("");
        
    }//GEN-LAST:event_btnRequestTestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestTest;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTestDone;
    private javax.swing.JScrollPane spTest;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtTestsDone;
    // End of variables declaration//GEN-END:variables
}
