/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import userinterface.InvestigatorRole.InvestigatorWorkAreaJPanel;

/**
 *
 * 
 */
public class ViewPatientDetailsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest request;
    /**
     * Creates new form ViewPatientDetailsJPanel
     */


    ViewPatientDetailsJPanel(JPanel userProcessContainer, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        populateFields();    
        
        Icon i = lblImg.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(lblImg.getWidth() , lblImg.getHeight(), Image.SCALE_SMOOTH);
        lblImg.setIcon(new ImageIcon(image));
    }

    public void populateFields(){
        txtName.setText(request.getChildName());
        txtGender.setText(request.getSex());
        txtMedicalIssues.setText(request.getKnownIssues());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblMedicalIssues = new javax.swing.JLabel();
        spMedicalIssues = new javax.swing.JScrollPane();
        txtMedicalIssues = new javax.swing.JTextArea();
        lblGender = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(null);

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtName);
        txtName.setBounds(266, 142, 196, 23);

        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtGender);
        txtGender.setBounds(621, 142, 141, 23);

        lblName.setBackground(new java.awt.Color(0, 0, 0));
        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Name of Child:");
        lblName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblName);
        lblName.setBounds(108, 142, 140, 21);

        lblMedicalIssues.setBackground(new java.awt.Color(0, 0, 0));
        lblMedicalIssues.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMedicalIssues.setText("Medical issues (if Any):");
        add(lblMedicalIssues);
        lblMedicalIssues.setBounds(150, 250, 200, 21);

        txtMedicalIssues.setColumns(20);
        txtMedicalIssues.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMedicalIssues.setRows(5);
        spMedicalIssues.setViewportView(txtMedicalIssues);

        add(spMedicalIssues);
        spMedicalIssues.setBounds(375, 214, 427, 111);

        lblGender.setBackground(new java.awt.Color(0, 0, 0));
        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGender.setText("Gender:");
        add(lblGender);
        lblGender.setBounds(502, 142, 101, 21);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(54, 40, 90, 37);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/doctor-6.png"))); // NOI18N
        lblImg.setToolTipText("");
        lblImg.setMaximumSize(new java.awt.Dimension(1680, 1050));
        lblImg.setMinimumSize(new java.awt.Dimension(1680, 1050));
        lblImg.setPreferredSize(new java.awt.Dimension(1680, 1050));
        add(lblImg);
        lblImg.setBounds(50, -130, 1680, 1050);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwajp = (DoctorWorkAreaJPanel) component;
        dwajp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblMedicalIssues;
    private javax.swing.JLabel lblName;
    private javax.swing.JScrollPane spMedicalIssues;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextArea txtMedicalIssues;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
