/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class ViewTestResultsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer; 
    LabTestWorkRequest request;
    /**
     * Creates new form ViewTestResultsJPanel
     */
    public ViewTestResultsJPanel() {
        initComponents();
        
    }

    ViewTestResultsJPanel(JPanel userProcessContainer, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        populateFields();
    }

    public void populateFields(){
        txtName.setText(request.getChildName());
        txtGender.setText(request.getSex());
        txtTestUndergone.setText(request.getTests());
        txtReport.setText(request.getTestReport());
        ImageIcon imageIcon = new ImageIcon(request.getXray());
        lblXray.setIcon(imageIcon);
        ImageIcon imageIcon1 = new ImageIcon(request.getCtScan());
        lblCtscan.setIcon(imageIcon1);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTestReport = new javax.swing.JScrollPane();
        txtReport = new javax.swing.JTextArea();
        lblTestReport = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblDender = new javax.swing.JLabel();
        spTestUndergone = new javax.swing.JScrollPane();
        txtTestUndergone = new javax.swing.JTextArea();
        lblTestUndergone = new javax.swing.JLabel();
        lblXRAY = new javax.swing.JLabel();
        lblCTSCAN = new javax.swing.JLabel();
        lblXray = new javax.swing.JLabel();
        lblCtscan = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 204));
        setLayout(null);

        txtReport.setColumns(20);
        txtReport.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtReport.setRows(5);
        spTestReport.setViewportView(txtReport);

        add(spTestReport);
        spTestReport.setBounds(225, 374, 341, 101);

        lblTestReport.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTestReport.setForeground(new java.awt.Color(255, 255, 255));
        lblTestReport.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTestReport.setText("Test Report:");
        add(lblTestReport);
        lblTestReport.setBounds(67, 399, 152, 46);

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtName);
        txtName.setBounds(225, 171, 338, 30);

        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender);
        txtGender.setBounds(670, 170, 128, 30);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Patient Name:");
        lblName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblName);
        lblName.setBounds(92, 174, 127, 21);

        lblDender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDender.setForeground(new java.awt.Color(255, 255, 255));
        lblDender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDender.setText("Gender:");
        add(lblDender);
        lblDender.setBounds(581, 169, 80, 30);

        txtTestUndergone.setColumns(20);
        txtTestUndergone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTestUndergone.setRows(5);
        spTestUndergone.setViewportView(txtTestUndergone);

        add(spTestUndergone);
        spTestUndergone.setBounds(225, 243, 338, 96);

        lblTestUndergone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTestUndergone.setForeground(new java.awt.Color(255, 255, 255));
        lblTestUndergone.setText("  Tests Undergone:");
        add(lblTestUndergone);
        lblTestUndergone.setBounds(70, 280, 200, 21);

        lblXRAY.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblXRAY.setForeground(new java.awt.Color(255, 255, 255));
        lblXRAY.setText("X-Ray:");
        add(lblXRAY);
        lblXRAY.setBounds(225, 26, 100, 21);

        lblCTSCAN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCTSCAN.setForeground(new java.awt.Color(255, 255, 255));
        lblCTSCAN.setText("CT-Scan:");
        add(lblCTSCAN);
        lblCTSCAN.setBounds(549, 26, 120, 21);

        lblXray.setText(".");
        add(lblXray);
        lblXray.setBounds(226, 69, 3, 16);

        lblCtscan.setText(".");
        add(lblCtscan);
        lblCtscan.setBounds(416, 69, 3, 16);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 17, 72, 36);
        add(lblImg);
        lblImg.setBounds(10, 0, 900, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwajp = (DoctorWorkAreaJPanel) component;
        dwajp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblCTSCAN;
    private javax.swing.JLabel lblCtscan;
    private javax.swing.JLabel lblDender;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTestReport;
    private javax.swing.JLabel lblTestUndergone;
    private javax.swing.JLabel lblXRAY;
    private javax.swing.JLabel lblXray;
    private javax.swing.JScrollPane spTestReport;
    private javax.swing.JScrollPane spTestUndergone;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtReport;
    private javax.swing.JTextArea txtTestUndergone;
    // End of variables declaration//GEN-END:variables
}
