/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InvestigatorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.PoliceDepartmentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class InvestigatorWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private PoliceDepartmentOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form InvestigatorWorkAreaJPanel
     */
    public InvestigatorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PoliceDepartmentOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        //valueLabel.setText(enterprise.getName());
        lblusername.setText(userAccount.getUsername());
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblWorkRequest.getModel();
        
        model.setRowCount(0);
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spRequestTable = new javax.swing.JScrollPane();
        tblWorkRequest = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnUpdateStatus = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        tblWorkRequest.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Child Name", "Reporting Official", "Investigator", "Case Status"
            }
        ));
        spRequestTable.setViewportView(tblWorkRequest);

        add(spRequestTable);
        spRequestTable.setBounds(220, 180, 620, 211);

        btnAssign.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAssign.setText("Assign to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign);
        btnAssign.setBounds(217, 440, 155, 50);

        btnUpdateStatus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });
        add(btnUpdateStatus);
        btnUpdateStatus.setBounds(682, 440, 155, 50);

        btnViewDetails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails);
        btnViewDetails.setBounds(450, 440, 155, 50);

        lblWelcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblWelcome.setText("Welcome");
        add(lblWelcome);
        lblWelcome.setBounds(49, 77, 94, 29);

        lblusername.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblusername.setText("username");
        add(lblusername);
        lblusername.setBounds(146, 77, 201, 29);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/investigation -2.jpg"))); // NOI18N
        add(lblImg);
        lblImg.setBounds(-1790, 110, 3150, 690);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
       int selectedRow = tblWorkRequest.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        LabTestWorkRequest request = (LabTestWorkRequest)tblWorkRequest.getValueAt(selectedRow, 0);
     
        
        InvestigatorChildAreaJPanel processWorkRequestJPanel = new InvestigatorChildAreaJPanel(userProcessContainer, request);
        userProcessContainer.add("InvestigatorChildAreaJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWorkRequest.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        LabTestWorkRequest request = (LabTestWorkRequest)tblWorkRequest.getValueAt(selectedRow, 0);
        
        if(request.getReceiver() == null){
        
            request.setStatus("Open");
        request.setReceiver(userAccount);
        JOptionPane.showMessageDialog(null, "Case Assigned Successfully");
        InvestigatorChildAreaJPanel processWorkRequestJPanel = new InvestigatorChildAreaJPanel(userProcessContainer, request);
        userProcessContainer.add("InvestigatorChildAreaJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "Case already Assigned");
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWorkRequest.getSelectedRow();
        if (selectedRow < 0){
            return;
        }
        
        LabTestWorkRequest request = (LabTestWorkRequest)tblWorkRequest.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Closed")){
            JOptionPane.showMessageDialog(null, "Case already closed");
        }else{
        if(request.getReceiver() == userAccount){
        InvestigatorReportAreaJPanel processWorkRequestJPanel = new InvestigatorReportAreaJPanel(userProcessContainer, request);
        userProcessContainer.add("InvestigatorReportAreaJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "You don't have the Permissions to access this Case");

        }
        }
    }//GEN-LAST:event_btnUpdateStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblusername;
    private javax.swing.JScrollPane spRequestTable;
    private javax.swing.JTable tblWorkRequest;
    // End of variables declaration//GEN-END:variables
}
