/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InvestigatorRole;

import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import userinterface.DoctorRole.DoctorWorkAreaJPanel;

/**
 *
 * 
 */
public class InvestigatorChildAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    LabTestWorkRequest request;
    /**
     * Creates new form InvestigatorChildAreaJPanel
     */


    InvestigatorChildAreaJPanel(JPanel userProcessContainer, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        populateFields();
    }
    
    public void populateFields(){
        txtName.setText(request.getChildName());
        txtGender.setText(request.getSex());
        txtEthnicity.setText(request.getEthnicity());
        txtWhen.setText(request.getWhenFound());
        txtWhere.setText(request.getWhereFound());
        txtDesc.setText(request.getDescribe());
        txtDetails.setText(request.getParentDetails());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblWhere = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        spDetails = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        lblEthnicity = new javax.swing.JLabel();
        lblWhen = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        spDesc = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        lblDetails = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtEthnicity = new javax.swing.JTextField();
        txtWhen = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        spWhere = new javax.swing.JScrollPane();
        txtWhere = new javax.swing.JTextArea();
        lblImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(230, 100, 100, 35);

        lblWhere.setBackground(new java.awt.Color(255, 255, 255));
        lblWhere.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblWhere.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWhere.setText("Where was the Child found:");
        lblWhere.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblWhere);
        lblWhere.setBounds(410, 340, 260, 21);

        lblGender.setBackground(new java.awt.Color(255, 255, 255));
        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGender.setText("Gender:");
        add(lblGender);
        lblGender.setBounds(590, 190, 70, 21);

        txtDetails.setBackground(new java.awt.Color(255, 255, 153));
        txtDetails.setColumns(20);
        txtDetails.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDetails.setRows(5);
        spDetails.setViewportView(txtDetails);

        add(spDetails);
        spDetails.setBounds(670, 520, 450, 85);

        lblEthnicity.setBackground(new java.awt.Color(255, 255, 255));
        lblEthnicity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblEthnicity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEthnicity.setText("Ethnicity:");
        lblEthnicity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblEthnicity);
        lblEthnicity.setBounds(570, 230, 90, 21);

        lblWhen.setBackground(new java.awt.Color(255, 255, 255));
        lblWhen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblWhen.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWhen.setText("When was the Child found:");
        lblWhen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblWhen);
        lblWhen.setBounds(420, 270, 240, 21);

        lblDesc.setBackground(new java.awt.Color(255, 255, 255));
        lblDesc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDesc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDesc.setText("Description of the Incident:");
        lblDesc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblDesc);
        lblDesc.setBounds(430, 440, 230, 21);

        txtDesc.setBackground(new java.awt.Color(255, 255, 153));
        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDesc.setRows(5);
        spDesc.setViewportView(txtDesc);

        add(spDesc);
        spDesc.setBounds(670, 420, 450, 85);

        lblDetails.setBackground(new java.awt.Color(255, 255, 255));
        lblDetails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDetails.setText("Details of Parents / Guardians Information:");
        add(lblDetails);
        lblDetails.setBounds(320, 550, 350, 21);

        txtName.setBackground(new java.awt.Color(255, 255, 153));
        txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName);
        txtName.setBounds(670, 150, 450, 23);

        txtGender.setBackground(new java.awt.Color(255, 255, 153));
        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(txtGender);
        txtGender.setBounds(670, 190, 450, 23);

        txtEthnicity.setBackground(new java.awt.Color(255, 255, 153));
        txtEthnicity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtEthnicity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEthnicityActionPerformed(evt);
            }
        });
        add(txtEthnicity);
        txtEthnicity.setBounds(670, 230, 450, 23);

        txtWhen.setBackground(new java.awt.Color(255, 255, 153));
        txtWhen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtWhen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWhenActionPerformed(evt);
            }
        });
        add(txtWhen);
        txtWhen.setBounds(670, 270, 450, 23);

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Child Name:");
        lblName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblName);
        lblName.setBounds(540, 150, 120, 21);

        txtWhere.setBackground(new java.awt.Color(255, 255, 153));
        txtWhere.setColumns(20);
        txtWhere.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtWhere.setRows(5);
        spWhere.setViewportView(txtWhere);

        add(spWhere);
        spWhere.setBounds(670, 310, 450, 85);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/investigation-2.jpg"))); // NOI18N
        lblImg.setPreferredSize(new java.awt.Dimension(500, 200));
        add(lblImg);
        lblImg.setBounds(-430, -50, 2270, 1250);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        InvestigatorWorkAreaJPanel iwajp = (InvestigatorWorkAreaJPanel) component;
        iwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEthnicityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEthnicityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEthnicityActionPerformed

    private void txtWhenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWhenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWhenActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblEthnicity;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblWhen;
    private javax.swing.JLabel lblWhere;
    private javax.swing.JScrollPane spDesc;
    private javax.swing.JScrollPane spDetails;
    private javax.swing.JScrollPane spWhere;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextArea txtDetails;
    private javax.swing.JTextField txtEthnicity;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtWhen;
    private javax.swing.JTextArea txtWhere;
    // End of variables declaration//GEN-END:variables
}
