/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BankManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.BankManagerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.LawyerRole.ViewFosterParentDocument;

/**
 *
 * 
 */
public class BankManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankManagerWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    BankManagerOrganization organization; 
    Enterprise enterprise;
    EcoSystem system;

    public BankManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, BankManagerOrganization bankManagerOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=account;
        this.organization=bankManagerOrganization;
        this.enterprise=enterprise;
        this.system=business;
        populateFields();
    }

    public void populateFields(){
        DefaultTableModel model = (DefaultTableModel) tblBank.getModel();
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[3];
            row[0] = request;
            row[1] = request.getDonationamount();
            row[2] = request.getBankapproval()==null||request.getBankapproval().isEmpty()?"Pending":"Approved";
            model.addRow(row);
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBank = new javax.swing.JTable();
        lblPayment = new javax.swing.JLabel();
        btnClick = new javax.swing.JButton();
        lblApproval = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        lblBG = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        tblBank.setBackground(new java.awt.Color(249, 241, 234));
        tblBank.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblBank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor Name", "Amount", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblBank);

        add(jScrollPane1);
        jScrollPane1.setBounds(228, 64, 452, 271);

        lblPayment.setBackground(new java.awt.Color(255, 255, 255));
        lblPayment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(255, 255, 255));
        lblPayment.setText("Payment Recieved Status:");
        add(lblPayment);
        lblPayment.setBounds(218, 389, 210, 21);

        btnClick.setBackground(new java.awt.Color(249, 241, 234));
        btnClick.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnClick.setText("Click ");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });
        add(btnClick);
        btnClick.setBounds(477, 386, 139, 28);

        lblApproval.setBackground(new java.awt.Color(255, 255, 255));
        lblApproval.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblApproval.setForeground(new java.awt.Color(255, 255, 255));
        lblApproval.setText("Approval:");
        add(lblApproval);
        lblApproval.setBounds(346, 441, 90, 21);

        btnView.setBackground(new java.awt.Color(249, 241, 234));
        btnView.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView);
        btnView.setBounds(477, 438, 139, 28);

        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bank-1.jpg"))); // NOI18N
        lblBG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(lblBG);
        lblBG.setBounds(0, 0, 1500, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBank.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        LabTestWorkRequest request = (LabTestWorkRequest)tblBank.getValueAt(selectedRow, 0);
        if(request.getBankapproval()=="Approved"){
            JOptionPane.showMessageDialog(null, "The payment has already been approved");
        }else{
        request.setBankapproval("Approved");
        WorkRequest.setBankbalance(WorkRequest.getBankbalance()+request.getDonationamount());
        if(request.getDonationamount()>WorkRequest.getHighestdonoramount()){
            WorkRequest.setHighestdonor(request.getChildName());
        }
            JOptionPane.showMessageDialog(null, "Payment has been Approved");
        }
        populateFields();
    }//GEN-LAST:event_btnClickActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBank.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        LabTestWorkRequest request = (LabTestWorkRequest)tblBank.getValueAt(selectedRow, 0);
        
        ViewJPanel processWorkRequestJPanel = new ViewJPanel(userProcessContainer, request, userAccount);
        userProcessContainer.add("ViewFosterParentDocument", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClick;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApproval;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JTable tblBank;
    // End of variables declaration//GEN-END:variables
}
