/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BankManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.BankManagerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.LawyerRole.ViewFosterParentDocument;

/**
 *
 * 
 */
public class BankManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankManagerWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    BankManagerOrganization organization; 
    Enterprise enterprise;
    EcoSystem system;

    public BankManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, BankManagerOrganization bankManagerOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=account;
        this.organization=bankManagerOrganization;
        this.enterprise=enterprise;
        this.system=business;
        populateFields();
    }

    public void populateFields(){
        DefaultTableModel model = (DefaultTableModel) tblBank.getModel();
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[3];
            row[0] = request;
            row[1] = request.getDonationamount();
            row[2] = request.getBankapproval()==null||request.getBankapproval().isEmpty()?"Pending":"Approved";
            model.addRow(row);
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBank = new javax.swing.JTable();
        lblPayment = new javax.swing.JLabel();
        btnClick = new javax.swing.JButton();
        lblApproval = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 204));

        tblBank.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblBank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor Name", "Amount", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblBank);

        lblPayment.setBackground(new java.awt.Color(255, 255, 255));
        lblPayment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPayment.setText("Payment Recieved Status:");

        btnClick.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnClick.setText("Click here");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });

        lblApproval.setBackground(new java.awt.Color(255, 255, 255));
        lblApproval.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblApproval.setText("Approval:");

        btnView.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblApproval)
                            .addComponent(lblPayment))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPayment)
                    .addComponent(btnClick))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApproval)
                    .addComponent(btnView))
                .addContainerGap(291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBank.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        LabTestWorkRequest request = (LabTestWorkRequest)tblBank.getValueAt(selectedRow, 0);
        if(request.getBankapproval()=="Approved"){
            JOptionPane.showMessageDialog(null, "The payment has already been approved");
        }else{
        request.setBankapproval("Approved");
        WorkRequest.setBankbalance(WorkRequest.getBankbalance()+request.getDonationamount());
        if(request.getDonationamount()>WorkRequest.getHighestdonoramount()){
            WorkRequest.setHighestdonor(request.getChildName());
        }
            JOptionPane.showMessageDialog(null, "Payment has been Approved");
        }
        populateFields();
    }//GEN-LAST:event_btnClickActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBank.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        LabTestWorkRequest request = (LabTestWorkRequest)tblBank.getValueAt(selectedRow, 0);
        
        ViewJPanel processWorkRequestJPanel = new ViewJPanel(userProcessContainer, request, userAccount);
        userProcessContainer.add("ViewFosterParentDocument", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClick;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApproval;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JTable tblBank;
    // End of variables declaration//GEN-END:variables
}
