/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BankManagerRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import userinterface.LawyerRole.LawyerWorkAreaJPanel;

/**
 *
 * 
 */
public class ViewJPanel extends javax.swing.JPanel {

JPanel userProcessContainer;
LabTestWorkRequest request;
UserAccount userAccount;

    ViewJPanel(JPanel userProcessContainer, LabTestWorkRequest request, UserAccount userAccount) {
                initComponents();
                this.userProcessContainer=userProcessContainer;
                this.request=request;
                this.userAccount=userAccount;
                populate();

    }
    public void populate(){
        txtLastName.setText(request.getChildName());
        txtDonationAmount.setText(request.getDonationamount()+"");
        txtPersonalMessage.setText(request.getDonormessage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        lblPersonalMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPersonalMessage = new javax.swing.JTextArea();
        lblName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblDonationAmount = new javax.swing.JLabel();
        txtDonationAmount = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblPersonalMessage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPersonalMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblPersonalMessage.setText("Personal Message:");
        add(lblPersonalMessage);
        lblPersonalMessage.setBounds(74, 280, 160, 21);

        txtPersonalMessage.setBackground(new java.awt.Color(249, 241, 234));
        txtPersonalMessage.setColumns(20);
        txtPersonalMessage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPersonalMessage.setRows(5);
        jScrollPane1.setViewportView(txtPersonalMessage);

        add(jScrollPane1);
        jScrollPane1.setBounds(329, 218, 240, 153);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name:");
        add(lblName);
        lblName.setBounds(168, 133, 70, 21);

        txtLastName.setBackground(new java.awt.Color(249, 241, 234));
        txtLastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtLastName);
        txtLastName.setBounds(329, 128, 240, 27);

        lblDonationAmount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDonationAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblDonationAmount.setText("Donation Amount:");
        add(lblDonationAmount);
        lblDonationAmount.setBounds(80, 180, 170, 21);

        txtDonationAmount.setBackground(new java.awt.Color(249, 241, 234));
        txtDonationAmount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtDonationAmount);
        txtDonationAmount.setBounds(329, 173, 240, 27);

        btnBack.setBackground(new java.awt.Color(249, 241, 234));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(53, 35, 72, 37);

        jLabel1.setBackground(new java.awt.Color(249, 241, 234));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/donation.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1600, 1069);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BankManagerWorkAreaJPanel dwajp = (BankManagerWorkAreaJPanel) component;
        dwajp.populateFields();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDonationAmount;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPersonalMessage;
    private javax.swing.JTextField txtDonationAmount;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextArea txtPersonalMessage;
    // End of variables declaration//GEN-END:variables
}
