/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabAssistantRole;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * 
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest request;
    JFileChooser image;
    Organization organization;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer, LabTestWorkRequest request, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.organization = organization;
        image=new JFileChooser();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTestReport = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnUploadXray = new javax.swing.JButton();
        btnCTScan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));
        setLayout(null);

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSubmit.setText("Submit Report");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(149, 520, 140, 37);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(42, 30, 100, 37);

        txtTestReport.setColumns(20);
        txtTestReport.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTestReport.setRows(5);
        jScrollPane1.setViewportView(txtTestReport);

        add(jScrollPane1);
        jScrollPane1.setBounds(149, 190, 544, 270);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Test Report");
        add(jLabel2);
        jLabel2.setBounds(340, 150, 150, 29);

        btnUploadXray.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUploadXray.setText("Upload X-Ray");
        btnUploadXray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadXrayActionPerformed(evt);
            }
        });
        add(btnUploadXray);
        btnUploadXray.setBounds(351, 520, 150, 37);

        btnCTScan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCTScan.setText("Upload CT-scan");
        btnCTScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTScanActionPerformed(evt);
            }
        });
        add(btnCTScan);
        btnCTScan.setBounds(540, 520, 150, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lab-assistant.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-20, -70, 1280, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabAssistantWorkAreaJPanel dwjp = (LabAssistantWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(txtTestReport.getText()==null || txtTestReport.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Test Report is Blank");
        }
        else{
        request.setTestReport(txtTestReport.getText()+"\n"+"\n>>Tests done by  "+organization.getEmployeeDirectory().getEmployeeList());
        request.setMedicalStatus("Complete");
        JOptionPane.showMessageDialog(null, "Test Report sent successfully");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUploadXrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadXrayActionPerformed
        // TODO add your handling code here:
        int returnVal= image.showOpenDialog(ProcessWorkRequestJPanel.this);
    if(returnVal == JFileChooser.APPROVE_OPTION)
    { 
        File file = image.getSelectedFile();
    String imagePath= file.getAbsolutePath();
    request.setXray(imagePath);
    }
    if(request.getXray()==null || request.getXray().isEmpty()){
        JOptionPane.showMessageDialog(null, "X-ray not uploaded");
    }
    else{
        JOptionPane.showMessageDialog(null, "X-ray uploaded successfully");
    }
    }//GEN-LAST:event_btnUploadXrayActionPerformed

    private void btnCTScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTScanActionPerformed
        // TODO add your handling code here:
         int returnVal= image.showOpenDialog(ProcessWorkRequestJPanel.this);
    if(returnVal == JFileChooser.APPROVE_OPTION)
    { 
        File file = image.getSelectedFile();
    String imagePath= file.getAbsolutePath();
    request.setCtScan(imagePath);
    }
    if(request.getCtScan()==null || request.getCtScan().isEmpty()){
        JOptionPane.showMessageDialog(null, "CT-scan not uploaded");
    }
        else{
                JOptionPane.showMessageDialog(null, "CT-scan uploaded successfully");
                }
    }//GEN-LAST:event_btnCTScanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCTScan;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUploadXray;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtTestReport;
    // End of variables declaration//GEN-END:variables
}
