/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabAssistantRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class ViewDetailsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest request;
    UserAccount userAccount;

    /**
     * Creates new form ViewDetailsJPanel
     */


    ViewDetailsJPanel(JPanel userProcessContainer, LabTestWorkRequest request, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.userAccount = userAccount;
        populateFields();     
    }

    public void populateFields(){
        txtName.setText(request.getChildName());
        txtGender.setText(request.getSex());
        txtLabTest.setText(request.getTests());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGender = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        spTestDone = new javax.swing.JScrollPane();
        txtLabTest = new javax.swing.JTextArea();
        lblTestsDone = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblIMg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        txtGender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender);
        txtGender.setBounds(492, 184, 160, 30);

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName);
        txtName.setBounds(492, 134, 160, 30);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Patient Name:");
        lblName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblName);
        lblName.setBounds(281, 137, 144, 20);

        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGender.setText("Gender:");
        add(lblGender);
        lblGender.setBounds(245, 182, 180, 30);

        txtLabTest.setColumns(20);
        txtLabTest.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLabTest.setRows(5);
        spTestDone.setViewportView(txtLabTest);

        add(spTestDone);
        spTestDone.setBounds(492, 232, 160, 91);

        lblTestsDone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTestsDone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTestsDone.setText("Tests to be Done:");
        add(lblTestsDone);
        lblTestsDone.setBounds(253, 262, 172, 21);

        btnAssign.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAssign.setText("Assign to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign);
        btnAssign.setBounds(410, 370, 151, 42);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(170, 40, 100, 39);

        lblIMg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/doctor-5.png"))); // NOI18N
        add(lblIMg);
        lblIMg.setBounds(0, 60, 1160, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        
        if(request.getAssistant() == null){
            request.setAssistant(userAccount);
            JOptionPane.showMessageDialog(null, "Tests successfully Assigned");
       
        }
        else{
            JOptionPane.showMessageDialog(null, "Tests already Assigned");

        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabAssistantWorkAreaJPanel dwjp = (LabAssistantWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblIMg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTestsDone;
    private javax.swing.JScrollPane spTestDone;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextArea txtLabTest;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
